# Generated by Django 5.2.7 on 2026-06-10 00:00

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("fleetpings", "0015_alter_discordpingtarget_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FleetPingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Short name to identify this template",
                        max_length=255,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="You can add notes about this template here if you want",
                        null=True,
                        verbose_name="Notes",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this template is enabled or not",
                        verbose_name="Is enabled",
                    ),
                ),
                (
                    "ping_target",
                    models.CharField(
                        blank=True,
                        help_text="Prefill the ping target.",
                        max_length=255,
                        verbose_name="Ping target",
                    ),
                ),
                (
                    "pre_ping",
                    models.BooleanField(
                        blank=True,
                        help_text="Prefill the pre-ping checkbox.",
                        null=True,
                        verbose_name="Pre-Ping",
                    ),
                ),
                (
                    "ping_channel",
                    models.CharField(
                        blank=True,
                        help_text="Prefill the ping channel.",
                        max_length=255,
                        verbose_name="Ping to",
                    ),
                ),
                (
                    "fleet_type",
                    models.CharField(
                        blank=True,
                        help_text="Prefill the fleet type.",
                        max_length=255,
                        verbose_name="Fleet type",
                    ),
                ),
                (
                    "fleet_commander",
                    models.CharField(
                        blank=True,
                        help_text="Prefill the FC name.",
                        max_length=255,
                        verbose_name="FC name",
                    ),
                ),
                (
                    "fleet_name",
                    models.CharField(
                        blank=True,
                        help_text="Prefill the fleet name.",
                        max_length=255,
                        verbose_name="Fleet name",
                    ),
                ),
                (
                    "formup_location",
                    models.CharField(
                        blank=True,
                        help_text="Prefill the formup location.",
                        max_length=255,
                        verbose_name="Formup location",
                    ),
                ),
                (
                    "formup_time",
                    models.CharField(
                        blank=True,
                        help_text="Prefill the formup time.",
                        max_length=255,
                        verbose_name="Formup time",
                    ),
                ),
                (
                    "formup_time_mode",
                    models.CharField(
                        blank=True,
                        choices=[("eve", "EVE time"), ("local", "Local time")],
                        help_text="Prefill the formup time mode.",
                        max_length=5,
                        verbose_name="Time zone",
                    ),
                ),
                (
                    "formup_now",
                    models.BooleanField(
                        blank=True,
                        help_text="Prefill the Formup NOW checkbox.",
                        null=True,
                        verbose_name="Formup NOW",
                    ),
                ),
                (
                    "fleet_duration",
                    models.CharField(
                        blank=True,
                        help_text="Prefill the fleet duration.",
                        max_length=255,
                        verbose_name="Duration",
                    ),
                ),
                (
                    "fleet_comms",
                    models.CharField(
                        blank=True,
                        help_text="Prefill the fleet comms.",
                        max_length=255,
                        verbose_name="Fleet comms",
                    ),
                ),
                (
                    "fleet_doctrine",
                    models.CharField(
                        blank=True,
                        help_text="Prefill the doctrine.",
                        max_length=255,
                        verbose_name="Doctrine",
                    ),
                ),
                (
                    "fleet_doctrine_url",
                    models.CharField(
                        blank=True,
                        help_text="Prefill the doctrine link.",
                        max_length=255,
                        verbose_name="Doctrine link",
                    ),
                ),
                (
                    "srp",
                    models.BooleanField(
                        blank=True,
                        help_text="Prefill the SRP checkbox.",
                        null=True,
                        verbose_name="SRP",
                    ),
                ),
                (
                    "srp_link",
                    models.BooleanField(
                        blank=True,
                        help_text="Prefill the create SRP link checkbox.",
                        null=True,
                        verbose_name="Create SRP link",
                    ),
                ),
                (
                    "additional_information",
                    models.TextField(
                        blank=True,
                        help_text="Prefill the additional information.",
                        verbose_name="Additional information",
                    ),
                ),
                (
                    "optimer",
                    models.BooleanField(
                        blank=True,
                        help_text="Prefill the create Optimer checkbox.",
                        null=True,
                        verbose_name="Create Optimer",
                    ),
                ),
                (
                    "restricted_to_group",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Restrict this template to the following groups…",
                        related_name="fleetpingtemplate_require_groups",
                        to="auth.group",
                        verbose_name="Group restrictions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fleet ping template",
                "verbose_name_plural": "Fleet ping templates",
                "default_permissions": (),
            },
        ),
    ]
