# Generated by Django 5.2.7 on 2026-06-10 00:00

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fleetpings", "0016_fleetpingtemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleetpingtemplate",
            name="use_main",
            field=models.BooleanField(
                blank=True,
                help_text="Prefill the Use main checkbox.",
                null=True,
                verbose_name="Use main",
            ),
        ),
    ]
